version: v3.0
name: HPC-OPS-CICD-TAG
on:
  repo-name: HCF-Private/hpc-ops
  type: git
  tag:
    name: Git事件触发
    from-branches:
    - master
  manual: enabled
variables:
  BK_CI_HOOK_SOURCE_BRANCH:
    value: master
    props:
      label: branch
      type: vuex-input
stages:
- name: stage-1
  label:
  - Build
  jobs:
    job_Cty:
      name: torch290+cu129+sm90
      runs-on:
        pool-name: docker
        hw-spec: Standard-M
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_base:H-1.7.0
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: code.tar.gz
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            tar -cvf code.tar.gz ./
            cat /sys/fs/cgroup/memory/memory.limit_in_bytes
      - name: upload-code.tar.gz
        id: ""
        uses: UploadArtifactory@8.*
        with:
          filePath: code.tar.gz
          downloadFiles: "[{\"path\":\"\",\"param\":\"\"}]"
          metadata: []
      - name: compile sm90
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip install build cmake
            make sm90
      - name: config pip for upload
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_N46:
      name: torch2100+cu129+sm90
      runs-on:
        pool-name: docker
        hw-spec: Standard-M
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_base:H-1.7.2
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: compile sm90
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip install build cmake
            make sm90
      - name: config pip for upload
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_sfp_sm90:
      name: torch2100+cu130+sm90
      runs-on:
        pool-name: docker
        hw-spec: Standard-M
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_base:H-1.7.3
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: compile sm90
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip install build cmake
            make sm90
      - name: config pip for upload
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_sfp_sm100:
      name: torch2100+cu130+sm100
      runs-on:
        pool-name: docker
        hw-spec: Standard-M
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_base:H-1.7.3
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: compile sm100
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip install build cmake
            make sm100
      - name: config pip for upload
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_sfp_multi_arch:
      name: Compile torch2100 cuda13.0 multi-arch
      runs-on:
        pool-name: docker
        hw-spec: Standard-M
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_base:H-1.7.3
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: compile multi-arch
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip install build cmake
            make fat-wheel
      - name: config pip for upload
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2

concurrency: {}
syntax-dialect: INHERIT
