version: v3.0
name: HPC-OPS-CICD
on:
  repo-name: HCF-Private/hpc-ops
  type: git
  mr:
    name: Git事件触发
    target-branches:
    - master
    action:
    - open
    - reopen
    - push-update
    block-mr: true
    skip-wip: false
  manual: enabled
variables:
  BK_CI_HOOK_SOURCE_BRANCH:
    value: master
    props:
      label: branch
      type: vuex-input
stages:
- name: stage-1
  label:
  - Build
  jobs:
    job_Cty:
      name: Compile PyTorch-2.7
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_infer:H-5.2.1-v1
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
      - name: code style check
        id: ""
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            make format-check
      - name: character check
        id: N_0
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            python3 tools/check-no-chinese.py
      - name: code.tar.gz
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            tar -cvf code.tar.gz ./
      - name: upload-code.tar.gz
        id: ""
        uses: UploadArtifactory@8.*
        with:
          filePath: code.tar.gz
          downloadFiles: "[{\"path\":\"\",\"param\":\"\"}]"
          metadata: []
      - name: complile whl
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            make wheel
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_lz_:
      name: Compile PyTorch-2.9
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_infer:H-6.2.1.dev32
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: complile whl
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            make wheel
      - name: config pip for upload
        id: NXn
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe

            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
    job_sfp:
      name: Compile PyTorch-2.10
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/hunyuan_infer/text2text_infer:H-6.5.1.dev46
      steps:
      - checkout:
          repo-id: rxOYK
        name: git clone and checkout
        with:
          refName: "${BK_CI_HOOK_SOURCE_BRANCH}"
          enableGitLfs: false
      - name: complile whl
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe
            cd ${{ci.workspace}}
            make wheel
      - name: config pip for upload
        id: NXn
        uses: linuxScript@1.*
        with:
          script: |-
            set -xe

            cd ${{ci.workspace}}
            pip config set global.index-url https://bkdevops:@mirrors.tencent.com/repository/pypi/tencent_pypi/simple/
            pip config set global.extra-index-url https://bkdevops:@mirrors.tencent.com/pypi/simple/
            pip config set global.timeout 600
            pip config set install.trusted-host mirrors.tencent.com
      - name: upload to pypi
        uses: DistributionToGeneric@1.*
        with:
          username: reedlauliu
          token: e0b4892c66d411f086b85254009bad14
          repo_category: pypi
          pypi_upload_arguments:
          - skip_existing
          - verbose
          distribution: dist/hpc*.whl
        retry-times: 2
- name: stage-2
  label:
  - Build
  jobs:
    job_4Xn:
      name: Test
      mutex:
        label: singleton
        queue-length: 5
      runs-on:
        pool-name: agentless
      steps:
      - name: download-code.tar.gz
        id: ""
        uses: JobScriptExecutionA@1.*
        with:
          envId:
          - dpzbvgzp
          account: reedlauliu
          shellScriptContent: |-
            #!/bin/bash
            set -xe
            echo ${{BK_CI_PROJECT_NAME}}
            echo ${{BK_CI_PIPELINE_ID}}
            echo ${{BK_CI_BUILD_ID}}
            echo ${{BK_CI_BUILD_NUM}}
            echo ${{BK_CI_BUILD_TASK_ID}}

            workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
            sudo mkdir -p ${workpath}
            cd ${workpath}

            sudo curl -L -O --user reedlauliu:063d7d21ae494ce73636f0f767a15ec5 "https://bkrepo.woa.com/generic/ds-opt/pipeline/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}/code.tar.gz"
          operatorType: PIPELINE_AUTHORIZER
      - name: untar-code
        uses: JobScriptExecutionA@1.*
        with:
          envId:
          - dpzbvgzp
          account: reedlauliu
          shellScriptContent: |-
            #!/bin/bash
            set -xe

            echo ${{BK_CI_PROJECT_NAME}}
            echo ${{BK_CI_PIPELINE_ID}}
            echo ${{BK_CI_BUILD_ID}}
            echo ${{BK_CI_BUILD_NUM}}
            echo ${{BK_CI_BUILD_TASK_ID}}

            workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
            sudo docker exec -t hpc-ops-cicd bash -c "cd ${workpath}/ && tar -xvf ./code.tar.gz"
      - name: make
        uses: JobScriptExecutionA@1.*
        with:
          envId:
          - dpzbvgzp
          account: reedlauliu
          shellScriptContent: |-
            #!/bin/bash

            set -xe

            echo ${{BK_CI_PROJECT_NAME}}
            echo ${{BK_CI_PIPELINE_ID}}
            echo ${{BK_CI_BUILD_ID}}
            echo ${{BK_CI_BUILD_NUM}}
            echo ${{BK_CI_BUILD_TASK_ID}}

            workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
            sudo docker exec -t hpc-ops-cicd bash -c "cd ${workpath}/ && make"
      - name: pytest
        id: yST
        uses: JobScriptExecutionA@1.*
        with:
          envId:
          - dpzbvgzp
          account: reedlauliu
          shellScriptContent: |-
            #!/bin/bash

            set -xe

            echo ${{BK_CI_PROJECT_NAME}}
            echo ${{BK_CI_PIPELINE_ID}}
            echo ${{BK_CI_BUILD_ID}}
            echo ${{BK_CI_BUILD_NUM}}
            echo ${{BK_CI_BUILD_TASK_ID}}

            workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
            sudo docker exec -t hpc-ops-cicd bash -c "pkill -9 python3 || true"
            sudo docker exec -t hpc-ops-cicd bash -c "cd ${workpath}/ && make test"
      - name: compute-sanitizer
        id: rL0
        uses: JobScriptExecutionA@1.*
        with:
          envId:
          - dpzbvgzp
          scriptTimeout: "18000"
          account: reedlauliu
          shellScriptContent: |-
            #!/bin/bash
            set -xe

            echo ${{BK_CI_PROJECT_NAME}}
            echo ${{BK_CI_PIPELINE_ID}}
            echo ${{BK_CI_BUILD_ID}}
            echo ${{BK_CI_BUILD_NUM}}
            echo ${{BK_CI_BUILD_TASK_ID}}

            workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
            sudo docker exec -t hpc-ops-cicd bash -c "pkill -9 python3 || true"
            sudo docker exec -t hpc-ops-cicd bash -c "cd ${workpath}/ && make sanitizer"
finally:
  job_SCd:
    name: clean temp file
    runs-on:
      pool-name: agentless
    steps:
    - name: clean
      uses: JobScriptExecutionA@1.*
      with:
        envId:
        - dpzbvgzp
        account: reedlauliu
        shellScriptContent: |-
          #!/bin/bash
          set -xe

          workpath=/data/landun/workspace/${{BK_CI_PROJECT_NAME}}/${{BK_CI_PIPELINE_ID}}/${{BK_CI_BUILD_ID}}
          sudo rm -rf $workpath
notices:
- if: FAILURE
  type:
  - email
  - wework-message
  receivers:
  - "${{ci.actor}}"
  content: "【${{ci.project_name}}】- 【${{ci.pipeline_name}}】#${{ci.build_num}} 执行失败，耗时${{ci.pipeline_execute_time}}, 触发人: ${{ci.actor}}。"
concurrency:
  queue-timeout-minutes: 10
syntax-dialect: INHERIT

