/*
 * UCL SHMEM API - Device-Host Common
 * This file enhances NVSHMEM device-host common functions and types
 */

#ifndef UCL_SHMEM_DEVICE_HOST_COMMON_CUH
#define UCL_SHMEM_DEVICE_HOST_COMMON_CUH

#include "device_host/nvshmem_common.cuh"

namespace ucl {
namespace shmem {

// Device prefix macro
#define SHMEMI_DEVICE_PREFIX NVSHMEMI_DEVICE_PREFIX

// Type repetition macros for RMA types
#define SHMEMI_REPT_FOR_STANDARD_RMA_TYPES(FN_TEMPLATE) \
    NVSHMEMI_REPT_FOR_STANDARD_RMA_TYPES(FN_TEMPLATE)

#define SHMEMI_REPT_FOR_STANDARD_RMA_TYPES_WITH_SCOPE(FN_TEMPLATE, SC) \
    NVSHMEMI_REPT_FOR_STANDARD_RMA_TYPES_WITH_SCOPE(FN_TEMPLATE, SC)

#define SHMEMI_REPT_FOR_STANDARD_RMA_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX) \
    NVSHMEMI_REPT_FOR_STANDARD_RMA_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX)

#define SHMEMI_REPT_FOR_STANDARD_RMA_TYPES_AND_SCOPES2(FN_TEMPLATE) \
    NVSHMEMI_REPT_FOR_STANDARD_RMA_TYPES_AND_SCOPES2(FN_TEMPLATE)

// Size repetition macros
#define SHMEMI_REPT_FOR_SIZES(FN_TEMPLATE) \
    NVSHMEMI_REPT_FOR_SIZES(FN_TEMPLATE)

#define SHMEMI_REPT_FOR_SIZES_WITH_TYPE(FN_TEMPLATE) \
    NVSHMEMI_REPT_FOR_SIZES_WITH_TYPE(FN_TEMPLATE)

#define SHMEMI_REPT_FOR_SIZES_WITH_SCOPE2(FN_TEMPLATE, SCOPE, SC_SUFFIX, SC_PREFIX) \
    NVSHMEMI_REPT_FOR_SIZES_WITH_SCOPE2(FN_TEMPLATE, SCOPE, SC_SUFFIX, SC_PREFIX)

// Wait types repetition macro
#define SHMEMI_REPT_FOR_WAIT_TYPES(FN_TEMPLATE) \
    NVSHMEMI_REPT_FOR_WAIT_TYPES(FN_TEMPLATE)

// Reduce types repetition macros
#define SHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES(FN_TEMPLATE, opname) \
    NVSHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES(FN_TEMPLATE, opname)

#define SHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES(FN_TEMPLATE, opname) \
    NVSHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES(FN_TEMPLATE, opname)

#define SHMEMI_REPT_FOR_ARITH_REDUCE_TYPES(FN_TEMPLATE, opname) \
    NVSHMEMI_REPT_FOR_ARITH_REDUCE_TYPES(FN_TEMPLATE, opname)

#define SHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname) \
    NVSHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname)

#define SHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname) \
    NVSHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname)

#define SHMEMI_REPT_FOR_ARITH_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname) \
    NVSHMEMI_REPT_FOR_ARITH_REDUCE_TYPES_WITH_SCOPE(FN_TEMPLATE, SC, opname)

#define SHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname) \
    NVSHMEMI_REPT_FOR_BITWISE_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname)

#define SHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname) \
    NVSHMEMI_REPT_FOR_STANDARD_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname)

#define SHMEMI_REPT_FOR_ARITH_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname) \
    NVSHMEMI_REPT_FOR_ARITH_REDUCE_TYPES_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX, opname)

#define SHMEMI_REPT_TYPES_AND_OPS_FOR_REDUCE(FN_TEMPLATE) \
    NVSHMEMI_REPT_TYPES_AND_OPS_FOR_REDUCE(FN_TEMPLATE)

#define SHMEMI_REPT_TYPES_AND_OPS_FOR_REDUCE_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX) \
    NVSHMEMI_REPT_TYPES_AND_OPS_FOR_REDUCE_WITH_SCOPE2(FN_TEMPLATE, SC, SC_SUFFIX, SC_PREFIX)

#define SHMEMI_REPT_TYPES_AND_OPS_AND_SCOPES2_FOR_REDUCE(FN_TEMPLATE) \
    NVSHMEMI_REPT_TYPES_AND_OPS_AND_SCOPES2_FOR_REDUCE(FN_TEMPLATE)

// Team utility macros
#define SHMEMI_TEAM_ROUND_UP_DIV(x, y) NVSHMEMI_TEAM_ROUND_UP_DIV(x, y)
#define SHMEMI_TEAM_ROUND_UP(x, y) NVSHMEMI_TEAM_ROUND_UP(x, y)
#define SHMEMI_FCOLLECT_LL128_CALC_PSYNC_SIZE(x, T) NVSHMEMI_FCOLLECT_LL128_CALC_PSYNC_SIZE(x, T)

// Sync size constants
constexpr int SHMEMI_SYNC_SIZE = NVSHMEMI_SYNC_SIZE;
constexpr int SHMEMI_BCAST_SYNC_SIZE = NVSHMEMI_BCAST_SYNC_SIZE;
constexpr int SHMEMI_ALLTOALL_SYNC_SIZE = NVSHMEMI_ALLTOALL_SYNC_SIZE;
constexpr int SHMEMI_WARP_SIZE = NVSHMEMI_WARP_SIZE;

// Thread index and group size macros
#define SHMEMI_DECL_THREAD_IDX_warp() NVSHMEMI_DECL_THREAD_IDX_warp()
#define SHMEMI_DECL_THREAD_IDX_block() NVSHMEMI_DECL_THREAD_IDX_block()
#define SHMEMI_DECL_THREAD_IDX_thread() NVSHMEMI_DECL_THREAD_IDX_thread()

#define SHMEMI_DECL_THREADGROUP_SIZE_warp() NVSHMEMI_DECL_THREADGROUP_SIZE_warp()
#define SHMEMI_DECL_THREADGROUP_SIZE_block() NVSHMEMI_DECL_THREADGROUP_SIZE_block()
#define SHMEMI_DECL_THREADGROUP_SIZE_thread() NVSHMEMI_DECL_THREADGROUP_SIZE_thread()

// Sync macros
#define SHMEMI_SYNC_warp() NVSHMEMI_SYNC_warp()
#define SHMEMI_SYNC_block() NVSHMEMI_SYNC_block()
#define SHMEMI_SYNC_thread() NVSHMEMI_SYNC_thread()

// fcollect algorithm type
enum fcollect_algo_t {
    FCOLLECT_DEFAULT = ::FCOLLECT_DEFAULT,
    FCOLLECT_LL8 = ::FCOLLECT_LL8,
    FCOLLECT_ONESHOT = ::FCOLLECT_ONESHOT,
    FCOLLECT_NVLS = ::FCOLLECT_NVLS,
    FCOLLECT_NVLS_LL = ::FCOLLECT_NVLS_LL,
    FCOLLECT_LL128 = ::FCOLLECT_LL128,
    FCOLLECT_INVALID = ::FCOLLECT_INVALID
};

// Team operation type
enum shmemi_team_op_t {
    SYNC = ::SYNC,
    ALLTOALL = ::ALLTOALL,
    BCAST = ::BCAST,
    FCOLLECT = ::FCOLLECT,
    REDUCE = ::REDUCE,
    FCOLLECT_128 = ::FCOLLECT_128,
    OP_SENTINEL = ::OP_SENTINEL
};

// Job connectivity type
enum shmemi_job_connectivity_t {
    SHMEMI_JOB_GPU_LDST_ATOMICS = NVSHMEMI_JOB_GPU_LDST_ATOMICS,
    SHMEMI_JOB_GPU_LDST = NVSHMEMI_JOB_GPU_LDST,
    SHMEMI_JOB_GPU_LDST_REMOTE_ATOMICS = NVSHMEMI_JOB_GPU_LDST_REMOTE_ATOMICS,
    SHMEMI_JOB_GPU_PROXY = NVSHMEMI_JOB_GPU_PROXY,
    SHMEMI_JOB_GPU_PROXY_CST = NVSHMEMI_JOB_GPU_PROXY_CST,
    SHMEMI_JOB_CONN_TYPE_MAX = NVSHMEMI_JOB_CONN_TYPE_MAX
};

// Call site ID enum
enum shmemi_call_site_id {
    SHMEMI_CALL_SITE_BARRIER = NVSHMEMI_CALL_SITE_BARRIER,
    SHMEMI_CALL_SITE_BARRIER_WARP = NVSHMEMI_CALL_SITE_BARRIER_WARP,
    SHMEMI_CALL_SITE_BARRIER_THREADBLOCK = NVSHMEMI_CALL_SITE_BARRIER_THREADBLOCK,
    SHMEMI_CALL_SITE_WAIT_UNTIL_GE = NVSHMEMI_CALL_SITE_WAIT_UNTIL_GE,
    SHMEMI_CALL_SITE_WAIT_UNTIL_EQ = NVSHMEMI_CALL_SITE_WAIT_UNTIL_EQ,
    SHMEMI_CALL_SITE_WAIT_UNTIL_NE = NVSHMEMI_CALL_SITE_WAIT_UNTIL_NE,
    SHMEMI_CALL_SITE_WAIT_UNTIL_GT = NVSHMEMI_CALL_SITE_WAIT_UNTIL_GT,
    SHMEMI_CALL_SITE_WAIT_UNTIL_LT = NVSHMEMI_CALL_SITE_WAIT_UNTIL_LT,
    SHMEMI_CALL_SITE_WAIT_UNTIL_LE = NVSHMEMI_CALL_SITE_WAIT_UNTIL_LE,
    SHMEMI_CALL_SITE_WAIT_NE = NVSHMEMI_CALL_SITE_WAIT_NE,
    SHMEMI_CALL_SITE_PROXY_CHECK_CHANNEL_AVAILABILITY = NVSHMEMI_CALL_SITE_PROXY_CHECK_CHANNEL_AVAILABILITY,
    SHMEMI_CALL_SITE_PROXY_ENFORCE_CONSISTENCY_AT_TARGET = NVSHMEMI_CALL_SITE_PROXY_ENFORCE_CONSISTENCY_AT_TARGET,
    SHMEMI_CALL_SITE_PROXY_GLOBAL_EXIT = NVSHMEMI_CALL_SITE_PROXY_GLOBAL_EXIT,
    SHMEMI_CALL_SITE_PROXY_QUIET = NVSHMEMI_CALL_SITE_PROXY_QUIET,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_GE = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_GE,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_EQ = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_EQ,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_NE = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_NE,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_GT = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_GT,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_LT = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_LT,
    SHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_LE = NVSHMEMI_CALL_SITE_SIGNAL_WAIT_UNTIL_LE,
    SHMEMI_CALL_SITE_AMO_FETCH_WAIT_FLAG = NVSHMEMI_CALL_SITE_AMO_FETCH_WAIT_FLAG,
    SHMEMI_CALL_SITE_AMO_FETCH_WAIT_DATA = NVSHMEMI_CALL_SITE_AMO_FETCH_WAIT_DATA,
    SHMEMI_CALL_SITE_G_WAIT_FLAG = NVSHMEMI_CALL_SITE_G_WAIT_FLAG,
    SHMEMI_CALL_SITE_SENTINEL = NVSHMEMI_CALL_SITE_SENTINEL
};

// Team ID type
enum shmem_team_id_t {
    SHMEM_TEAM_INVALID = NVSHMEM_TEAM_INVALID,
    SHMEM_TEAM_WORLD = NVSHMEM_TEAM_WORLD,
    SHMEM_TEAM_WORLD_INDEX = NVSHMEM_TEAM_WORLD_INDEX,
    SHMEM_TEAM_SHARED = NVSHMEM_TEAM_SHARED,
    SHMEM_TEAM_SHARED_INDEX = NVSHMEM_TEAM_SHARED_INDEX,
    SHMEMX_TEAM_NODE = NVSHMEMX_TEAM_NODE,
    SHMEM_TEAM_NODE_INDEX = NVSHMEM_TEAM_NODE_INDEX,
    SHMEMX_TEAM_SAME_MYPE_NODE = NVSHMEMX_TEAM_SAME_MYPE_NODE,
    SHMEM_TEAM_SAME_MYPE_NODE_INDEX = NVSHMEM_TEAM_SAME_MYPE_NODE_INDEX,
    SHMEMI_TEAM_SAME_GPU = NVSHMEMI_TEAM_SAME_GPU,
    SHMEM_TEAM_SAME_GPU_INDEX = NVSHMEM_TEAM_SAME_GPU_INDEX,
    SHMEMI_TEAM_GPU_LEADERS = NVSHMEMI_TEAM_GPU_LEADERS,
    SHMEM_TEAM_GPU_LEADERS_INDEX = NVSHMEM_TEAM_GPU_LEADERS_INDEX,
    SHMEM_TEAMS_MIN = NVSHMEM_TEAMS_MIN,
    SHMEM_TEAM_INDEX_MAX = NVSHMEM_TEAM_INDEX_MAX
};

// Reduction operations type
enum rdxn_ops_t {
    RDXN_OPS_AND = ::RDXN_OPS_AND,
    RDXN_OPS_and = ::RDXN_OPS_and,
    RDXN_OPS_OR = ::RDXN_OPS_OR,
    RDXN_OPS_or = ::RDXN_OPS_or,
    RDXN_OPS_XOR = ::RDXN_OPS_XOR,
    RDXN_OPS_xor = ::RDXN_OPS_xor,
    RDXN_OPS_MIN = ::RDXN_OPS_MIN,
    RDXN_OPS_min = ::RDXN_OPS_min,
    RDXN_OPS_MAX = ::RDXN_OPS_MAX,
    RDXN_OPS_max = ::RDXN_OPS_max,
    RDXN_OPS_SUM = ::RDXN_OPS_SUM,
    RDXN_OPS_sum = ::RDXN_OPS_sum,
    RDXN_OPS_PROD = ::RDXN_OPS_PROD,
    RDXN_OPS_prod = ::RDXN_OPS_prod,
    RDXN_OPS_MAXLOC = ::RDXN_OPS_MAXLOC,
    RDXN_OPS_maxloc = ::RDXN_OPS_maxloc,
    RDXN_OPS_sentinel = ::RDXN_OPS_sentinel
};

// Proxy status type
enum shmemi_proxy_status {
    SHMEMI_PROXY_NONE = NVSHMEMI_PROXY_NONE,
    SHMEMI_PROXY_MINIMAL = NVSHMEMI_PROXY_MINIMAL,
    SHMEMI_PROXY_FULL = NVSHMEMI_PROXY_FULL,
    SHMEMI_PROXY_SENTINEL = NVSHMEMI_PROXY_SENTINEL
};

// Version structure
using shmemi_version_t = nvshmemi_version_t;
// Device library init callback type
using shmemx_device_lib_init_cb = nvshmemx_device_lib_init_cb;

#if !defined __CUDACC_RTC__

// Host library init with attributes
inline int shmemid_hostlib_init_attr(int requested, int *provided, unsigned int bootstrap_flags,
                                     nvshmemx_init_attr_t *attr,
                                     shmemi_version_t shmem_device_lib_version,
                                     shmemx_device_lib_init_cb cb) {
    return nvshmemid_hostlib_init_attr(requested, provided, bootstrap_flags, attr,
                                       shmem_device_lib_version, cb);
}

// Host library finalize
inline void shmemid_hostlib_finalize(void *device_ctx, void *transport_device_ctx) {
    nvshmemid_hostlib_finalize(device_ctx, transport_device_ctx);
}

// Init status query
inline int shmemid_init_status() {
    return nvshmemid_init_status();
}

#endif // !defined __CUDACC_RTC__

} // namespace shmem
} // namespace ucl

#endif // UCL_SHMEM_DEVICE_HOST_COMMON_CUH
